export const BASE_URL = 'https://62286b649fd6174ca82321f1.mockapi.io/case-study/';;

export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILD = 'GET_PRODUCTS_FAILD';

export const GET_PRODUCT_DETAIL_START = 'GET_PRODUCT_DETAIL_START';
export const GET_PRODUCTS_DETAIL_SUCCESS = 'GET_PRODUCTS_DETAIL_SUCCESS';
export const GET_PRODUCTS_DETAIL_FAILD = 'GET_PRODUCTS_DETAIL_FAILD';


export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILD = 'GET_CATEGORIES_FAILD';


export const ADD_PRODUCTS_START = 'ADD_PRODUCTS_START';
export const ADD_PRODUCTS_SUCCESS = 'ADD_PRODUCTS_SUCCESS';
export const ADD_PRODUCTS_FAILD = 'ADD_PRODUCTS_FAILD';

export const CLEAR_ADD_PRODUCTS = 'CLEAR_ADD_PRODUCTS';







